version: v0.0.20
name: lenix
author: Lenix
$minFxVersion: 17000
$onesync: on

tasks:
    - action: connect_database

    - action: download_github
      src: lenixdev/recipe
      subpath: config
      dest: ./config

    - action: download_file
      url: https://raw.githubusercontent.com/lenixdev/recipe/refs/heads/main/server.cfg
      path: ./server.cfg

    - action: download_file
      path: ./tmp/tr_lib.zip
      url: https://github.com/tripplerscripts/tr_lib/releases/latest/download/tr_lib.zip
    - action: unzip
      src: ./tmp/tr_lib.zip
      dest: ./resources/[trippler]

    - action: download_file
      path: ./tmp/tr_kit.zip
      url: https://github.com/tripplerscripts/tr_kit/releases/latest/download/tr_kit.zip
    - action: unzip
      src: ./tmp/tr_kit.zip
      dest: ./resources/[trippler]

    - action: download_github
      src: qbox-project/qbx_core
      dest: ./resources/[qbx_core]/qbx_core
    - action: query_database
      file: ./resources/[qbx_core]/qbx_core/qbx_core.sql

    - action: download_file
      path: ./tmp/ox_lib.zip
      url: https://github.com/communityox/ox_lib/releases/latest/download/ox_lib.zip
    - action: unzip
      src: ./tmp/ox_lib.zip
      dest: ./resources/[qbx_core]/[mandatories]

    - action: download_file
      path: ./tmp/oxmysql.zip
      url: https://github.com/communityox/oxmysql/releases/latest/download/oxmysql.zip
    - action: unzip
      src: ./tmp/oxmysql.zip
      dest: ./resources/[qbx_core]/[mandatories]

    - action: download_file
      path: ./tmp/ox_inventory.zip
      url: https://github.com/communityox/ox_inventory/releases/latest/download/ox_inventory.zip
    - action: unzip
      src: ./tmp/ox_inventory.zip
      dest: ./resources/[qbx_core]/[mandatories]

    - action: download_file
      path: ./tmp/ox_target.zip
      url: https://github.com/communityox/ox_target/releases/latest/download/ox_target.zip
    - action: unzip
      src: ./tmp/ox_target.zip
      dest: ./resources/[qbx_core]/[mandatories]

    - action: download_github
      src: qbox-project/qbx_vehicles
      dest: ./resources/[qbx_core]/[dependencies]/qbx_vehicles
    - action: query_database
      file: ./resources/[qbx_core]/[dependencies]/qbx_vehicles/vehicles.sql

    - action: download_github
      src: qbox-project/qbx_vehiclekeys
      dest: ./resources/[qbx_core]/[dependencies]/qbx_vehiclekeys

    - action: download_file
      path: ./tmp/Renewed-Banking.zip
      url: https://github.com/Renewed-Scripts/Renewed-Banking/releases/latest/download/Renewed-Banking.zip
    - action: unzip
      dest: ./resources/[qbx_core]/[dependencies]
      src: ./tmp/Renewed-Banking.zip
    - action: query_database
      file: ./resources/[qbx_core]/[dependencies]/Renewed-Banking/Renewed-Banking.sql

    - action: download_file
      path: ./tmp/illenium-appearance.zip
      url: https://github.com/iLLeniumStudios/illenium-appearance/releases/latest/download/illenium-appearance.zip
    - action: unzip
      dest: ./resources/[qbx_core]/[dependencies]
      src: ./tmp/illenium-appearance.zip
    - action: query_database
      file: ./resources/[qbx_core]/[dependencies]/illenium-appearance/sql/management_outfits.sql
    - action: query_database
      file: ./resources/[qbx_core]/[dependencies]/illenium-appearance/sql/player_outfit_codes.sql
    - action: query_database
      file: ./resources/[qbx_core]/[dependencies]/illenium-appearance/sql/player_outfits.sql
    - action: query_database
      file: ./resources/[qbx_core]/[dependencies]/illenium-appearance/sql/playerskins.sql


    - action: download_github
      src: https://github.com/citizenfx/cfx-server-data
      subpath: resources/[managers]/spawnmanager
      dest: ./resources/[qbx_core]/[dependencies]/spawnmanager

    - action: remove_path
      path: ./tmp